name: Daily Job Search

on:
  schedule:
    # 3:30 PM UTC = 9:00 PM IST
    - cron: '30 15 * * *'
  workflow_dispatch: # Allows manual run

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Pipeline
        env:
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GH_MODELS_API_KEY: ${{ secrets.GH_MODELS_API_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_APP_PASSWORD: ${{ secrets.SENDER_APP_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python main.py